### ISSUE TITLE
Что в версии 1.2

### ISSUE THREAD

**Issue by SonkinS** [Delo-Design/radicalmultifield#1]
Здравствуйте!

А что нового в релизе 1.2?
Может есть страница расширения или ветка на форуме?

**Comment by progreccor** [comment]
исправление ошибок. позже будет залито на гитхаб

**Comment by dmitriitux** [comment]
Описание есть, вот страница: https://hika.su/rasshireniya/raficalmultfild, она еще пополняется. Релиз был залит.
