### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by zikkuratvk** [Delo-Design/radicalmultifield#10]
1. Не обновляется список папок если создано через другой медиа менеджер.
2. При массовой заливке он добавляет свои цифры к названию картинки.
3. На разрешении 1333 верстка едет.
4. Не помнит в какой папке находился, каждый раз надо искать папку заново

**Comment by proweb** [comment]
При большом количестве картинок загруженных в поле - все начинает подвисать и тормозить

**Comment by dmitriitux** [comment]
сделать lowercase расширениям

**Comment by dmitriitux** [comment]
> При большом количестве картинок загруженных в поле - все начинает подвисать и тормозить

много - это сколько?

**Comment by dmitriitux** [comment]
> При большом количестве картинок загруженных в поле - все начинает подвисать и тормозить



> При большом количестве картинок загруженных в поле - все начинает подвисать и тормозить

Перенесено в https://github.com/JPathRu/radicalmultifield/issues/12

**Comment by dmitriitux** [comment]
> 1. Не обновляется список папок если создано через другой медиа менеджер.
> 2. При массовой заливке он добавляет свои цифры к названию картинки.
> 3. На разрешении 1333 верстка едет.
> 4. Не помнит в какой папке находился, каждый раз надо искать папку заново

В версии 2.2 исправлено все.
https://github.com/JPathRu/radicalmultifield/releases/tag/2.2
