### ISSUE TITLE
Сохранять последнюю открытую папку

### ISSUE THREAD

**Issue by progreccor** [Delo-Design/radicalmultifield#11]
При повторном открытии окошка импорта каждый раз возвращаемся в начало каталога. Если у нас сложная структура папок - это все понижает производительность очень сильно.
Надо сохранять последнюю открытую папку

**Comment by dmitriitux** [comment]
В версии 2.2 появилось.
https://github.com/JPathRu/radicalmultifield/releases/tag/2.2
