### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by SonkinS** [Delo-Design/radicalmultifield#2]
Здравствуйте.

Добавьте пожалуйста тип поля SQL. Просто сам тип в params\radicalmultifield.xml, чтоб в обновлениях был.

Если добавить вручную, всё вроде работает нормально, параметры запроса к базе через атрибуты поля срабатывают.

Спасибо.

**Comment by dmitriitux** [comment]
Здравствуйте, хорошо, добавим. Вы так же можете подключать свои кастомные поля (указав в настройках плагина пути до этих полей, классов php).

**Comment by dmitriitux** [comment]
[Добавили поле в параметры](https://github.com/Delo-Design/radicalmultifield/commit/0d3494ed18524688a4a3d936d10d2268032056b1)
