### ISSUE TITLE
Не работают превью

### ISSUE THREAD

**Issue by bsakhanov** [Delo-Design/radicalmultifield#3]
Почему бы не создать для галереи функцию создания миниатюр с задаваемыми размерами кропинга в произвольно выбранную директорию? Причем для кропинга можно было бы использовать php-функционал ранее созданного для [Joomla 3.7 плагина галереи для дополнительных полей из ядра Joomla](https://docs.joomla.org/J3.x:Adding_custom_fields/Gallery_Field). Потом почему-то этот плагин выпилили разрабы джумлы в более поздних версиях CMS) . Прикрепляю файл данного плагина. Посмотрите, плиз.
[gallery-fields.zip](https://github.com/Delo-Design/radicalmultifield/files/2629090/gallery-fields.zip)

А вот моя версия данного плагина для uikit3 -- 
[gallery.zip](https://github.com/Delo-Design/radicalmultifield/files/2629104/gallery.zip)

**Comment by dmitriitux** [comment]
Здравствуйте, кроппинг на самом деле уже есть в поле (сторонняя либа загружена), сейчас реализованы плагины, которые добавляют виртуальные поля.
Вот список на данный момент: https://hika.su/rasshireniya/raficalmultfild/katalog-plaginov
И пример плагина аудоплеера: https://github.com/Delo-Design/radicalmultifield_audioplayer
Для юкита создам отдельно плагин, шаблоны оставил в "core поле" для совместимости версий.
Да, и там для плагинов галерей будут потом добавлены превью.

**Comment by bsakhanov** [comment]
ок. понял

**Comment by bsakhanov** [comment]
Добрый день, Дмитрий! Спасибо за добавление возможности генерации превью! Просто супер!
Однако, начал было юзать последнюю версию, превью в админке появились, а на фронтенде -- их нет....
Полный адрес как до картинок, так и до превью -- не выставляется. Просто слеш на главную ведет, хотя сам список карточек галереи вроде и подгружается... В чем может быть дело?
На двух хостингах проверил -- одинаковая картина. Хотя сами превьюшки создаются и лежат в нужной папке...
![2019-02-24_203501](https://user-images.githubusercontent.com/45456925/53300607-ebcd3700-3873-11e9-94a4-a1b08aa3a420.jpg)

**Comment by dmitriitux** [comment]
@bsakhanov вы можете прислать код шаблона, который используется?

**Comment by bsakhanov** [comment]
используется стандартный шаблон "galleryforuikit3", естественно, также используется и основной плагин Radical Multi Field, посмотрите сами, доступы к тестовому сайту test.derma.kz выслал вам на почту от beibit@sakhanov.kz, если нужен доступ по ftp -- вышлю.

**Comment by bsakhanov** [comment]
тестовая страница: http://www.test.derma.kz/ru/news/641-45-studentov-plokho-predstavlyayut-sut-vybrannoj-professii

**Comment by dmitriitux** [comment]
> используется стандартный шаблон "galleryforuikit3", естественно, также используется и основной плагин Radical Multi Field, посмотрите сами, доступы к тестовому сайту test.derma.kz выслал вам на почту от [beibit@sakhanov.kz](mailto:beibit@sakhanov.kz), если нужен доступ по ftp -- вышлю.

пока не получил, можете еще раз выслать?

**Comment by bsakhanov** [comment]
выслал в ручном режиме, включая фтп

**Comment by bsakhanov** [comment]
на @gmail.com

**Comment by dmitriitux** [comment]
> выслал в ручном режиме, включая фтп

получил, щас просмотрю

**Comment by dmitriitux** [comment]
Проблема решена: 
1) Требовалось указать для стандартного шаблона имя полей: image и alt
2) Не было установлено расширение fileinfo для php

**Comment by b2z** [comment]
@dmitriitux а fileinfo вроде не очень специфичное? Но всё равно, может сделать проверку на существование функции?

**Comment by AlekVolsk** [comment]
требование к именам полей - слишком жёсткое

**Comment by dmitriitux** [comment]
> @dmitriitux а fileinfo вроде не очень специфичное? Но всё равно, может сделать проверку на существование функции?

думаю над этим, надо добавлять

**Comment by dmitriitux** [comment]
> требование к именам полей - слишком жёсткое

это для шаблонов стандартных, я думаю это решить немного иначе
