### ISSUE TITLE
Ошибка при редактировании материала в Joomla! 5.0.2

### ISSUE THREAD

**Issue by MSGroupFM** [Delo-Design/radicalmultifield#35]
При попытке перейти к редактированию материала получаю ошибку
`Class "JFormFieldQuantumupload" not found`

### Версия ПО
- php 8.2.13
- Joomla 5.0.2
- Пакет - Quantum Manager 3.0.0 
- Lib fields 2.0.3
- Поле - Radical MultiField 3.1.0

### Способ воспроизведения

1. Создать поле типа radicalmultifield
2. Включить настройку Разрешить импорт файлов
3. Перейти к редактированию или созданию материала
4. Вместо формы редактирования материала высветится ошибка, описанная выше

**Comment by dmitriitux** [comment]
обновление выйдет на днях и все будет поправлено
