### ISSUE TITLE
Class "JFormFieldQuantumupload" not found

### ISSUE THREAD

**Issue by jazz-max** [Delo-Design/radicalmultifield#36]
Joomla 4 
При установленном QUANTUMMANAGER "3.8" 
При включенном "импорте" 
Ошибка 
 Class "JFormFieldQuantumupload" not found 
 /plugins/fields/radicalmultifield/layouts/joomla4/import.php:18 (нужного файла там нет)

**Comment by dmitriitux** [comment]
сейчас обновление будет скоро, все поправлено
